return {
	require('modules/cmd_handler'),
	require('modules/money'),
	require('modules/privilages'),
	require('modules/privilages_events'),
	require('modules/admin'),
	require('modules/economy'),
	require('modules/say'),
	require('modules/nekos'),
	require('modules/voice'),
	require('modules/fox'),
	require('modules/avatar'),
	require('modules/triggers'),
	require('modules/ggappeals'),
	require('modules/qiwidonat'),
	require('modules/accounts_link'),
--	require('modules/test'),
	require('modules/subnews'),
	require('modules/ggevents_schedule'),
	require('modules/cats'),
	require('modules/dog'),
	require('modules/cleardata'),
}
