command_handler.register('say', 'Сказать <text>', '<text>', false, function (msg, argv, args)
	msg.channel:broadcastTyping()
	table.remove(argv, 1)
	msg:reply(table.concat(argv, ' '))
end)

command_handler.register('sayd', 'Сказать <text> и удалить ваше сообщение', '<text>', false, function (msg, argv, args)
	msg.channel:broadcastTyping()
	table.remove(argv, 1)
	msg:reply(table.concat(argv, ' '))
	msg:delete()
end)
